apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "prepforge.fullname" . }}-backend
  labels:
    {{- include "prepforge.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  {{- if not .Values.backend.autoscaling.enabled }}
  replicas: {{ .Values.backend.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "prepforge.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: backend
  template:
    metadata:
      labels:
        {{- include "prepforge.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: backend
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        prometheus.io/port: "8000"
    spec:
      containers:
        - name: backend
          image: {{ include "prepforge.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef: { name: {{ include "prepforge.fullname" . }}-config }
            - secretRef: { name: {{ include "prepforge.fullname" . }}-secrets }
          readinessProbe:
            httpGet: { path: /ready, port: 8000 }
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet: { path: /health, port: 8000 }
            initialDelaySeconds: 15
            periodSeconds: 20
          resources:
            {{- toYaml .Values.backend.resources | nindent 12 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "prepforge.fullname" . }}-backend
  labels:
    {{- include "prepforge.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "prepforge.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: backend
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
{{- if .Values.worker.enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "prepforge.fullname" . }}-worker
  labels:
    {{- include "prepforge.labels" . | nindent 4 }}
    app.kubernetes.io/component: worker
spec:
  replicas: {{ .Values.worker.replicaCount }}
  selector:
    matchLabels:
      {{- include "prepforge.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: worker
  template:
    metadata:
      labels:
        {{- include "prepforge.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: worker
    spec:
      containers:
        - name: worker
          image: {{ include "prepforge.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["celery", "-A", "app.worker.celery_app", "worker", "--loglevel=info"]
          envFrom:
            - configMapRef: { name: {{ include "prepforge.fullname" . }}-config }
            - secretRef: { name: {{ include "prepforge.fullname" . }}-secrets }
          resources:
            {{- toYaml .Values.worker.resources | nindent 12 }}
{{- end }}
